### ISSUE TITLE
NOT AN ISSUE

### ISSUE THREAD

**Issue by robcore** [ThePBone/DDCToolbox-Android#1]
I just didn't know how else to contact you with my encouragement and gratitude for these ddc projects!  Seriously, even the android version is extremely useful (having some issues with saving projects, but exporting to .vdc works just fine and I am NOT complaining).  Just wanted to stop by and say "thanks."  I would offer to help with the apk, but am all thumbs when it comes to java/kotlin/app development.  If you ever want to experiment with kernel-level biquads, I would be your man though.  Anyhow, feel free to close this and take care!
Rob

**Comment by timschneeb** [comment]
Thanks a lot!

I'm aware of some minor bugs in there but the project saving issue is new to me. I stopped working on this repo since there wasn't really a demand for an Android port but I'll try to get started with it again and hopefully patch those bugs out (+ maybe add AutoEQ integration or some other features from the Desktop version to it).

**Comment by robcore** [comment]
![Screenshot_2020-07-20-20-17-12](https://user-images.githubusercontent.com/2672544/88005617-063a2d00-cac7-11ea-83ad-d761b4d77162.png)
![Screenshot_2020-07-20-20-17-00](https://user-images.githubusercontent.com/2672544/88005625-0a664a80-cac7-11ea-9d5b-744a1bdd6ed1.png)

For sure! I really can't express how neat this is.  I'm a kernel programmer with an...unhealthy obsession with audio, so this little app has me tweaking vdc's for hours on end.  I'll attach screenshots of the little bugs I found but they still sorta work (I just mash where the button should be for projects, and enough of the export vdc button is visible to tap) 

Betcha you'd have a lot of interest if you submitted a post on xda :) take care!

**Comment by timschneeb** [comment]
Hmm, that's a large DPI setting. But I'll try to distribute the layout children a bit better, that should help.
XDA is a good idea, until now I only posted it in the JamesDSP Telegram group once and added a link in the README of the Desktop version.

**Comment by timschneeb** [comment]
A new update is available:
<https://github.com/ThePBone/DDCToolbox-Android/releases/tag/1.1>


It should work even on the smallest screens now:

![photo_2020-07-21_15-58-03](https://user-images.githubusercontent.com/38386967/88063969-fa07ab80-cb6a-11ea-80d8-267112c3ee3e.jpg)

**Comment by robcore** [comment]
Awesome! Works perfectly!  Only thing I should mention is that it isn't signed so I signed it with the generic android debug keys.  But I can see everything and man you are a genius!

**Comment by timschneeb** [comment]
It is signed using my personal keystore certificate but since I don't have a Google Play Dev License, it is not registered in Google's certificate database (and causes Google Play Protect to show a 'unknown developer' warning for example). 

I'll close this issue now. Thanks for the submission and feel free to open another one if you have feature requests or find more bugs :D
